import React from "react";
import { AiOutlineOrderedList } from "react-icons/ai";
import { BsTags } from "react-icons/bs";
import {
  HiOutlineChartSquareBar,
  HiOutlineUserGroup,
  HiOutlineTrendingUp,
  HiOutlineUserCircle,
  HiOutlineBookOpen,
  HiOutlineCurrencyDollar,
  HiOutlineShieldCheck,
  HiOutlineColorSwatch,
  HiOutlineChatAlt,
  HiOutlineDesktopComputer,
  HiOutlinePaperAirplane,
  HiOutlineChartPie,
  HiOutlineUserAdd,
  HiOutlineKey,
  HiOutlineBan,
  HiOutlineHand,
  HiOutlineDocumentText,
  HiOutlineTemplate,
  HiOutlineLockClosed,
  HiOutlineDocumentDuplicate,
  HiOutlineViewGridAdd,
  HiOutlineShare,
  HiOutlineVariable,
  HiOutlineCode,
  HiOutlineHome,
  HiOutlineGift,
  HiOutlineDatabase,
  HiOutlinePlusCircle,
  HiOutlineTag,
  HiOutlineShoppingBag
} from "react-icons/hi";
import { MdOutlineBookmarks, MdOutlineContentCopy } from "react-icons/md";

const navigationIcon = {
  apps: <HiOutlineViewGridAdd />,
  project: <HiOutlineChartSquareBar />,
  crm: <HiOutlineUserGroup />,
  sales: <HiOutlineTrendingUp />,
  crypto: <HiOutlineCurrencyDollar />,
  knowledgeBase: <HiOutlineBookOpen />,
  account: <HiOutlineUserCircle />,
  uiComponents: <HiOutlineTemplate />,
  common: <HiOutlineColorSwatch />,
  feedback: <HiOutlineChatAlt />,
  dataDisplay: <HiOutlineDesktopComputer />,
  forms: <HiOutlineDocumentText />,
  navigation: <HiOutlinePaperAirplane />,
  graph: <HiOutlineChartPie />,
  authentication: <HiOutlineLockClosed />,
  signIn: <HiOutlineShieldCheck />,
  signUp: <HiOutlineUserAdd />,
  forgotPassword: <HiOutlineLockClosed />,
  resetPassword: <HiOutlineKey />,
  pages: <HiOutlineDocumentDuplicate />,
  welcome: <HiOutlineHand />,
  accessDenied: <HiOutlineBan />,
  guide: <HiOutlineBookOpen />,
  documentation: <HiOutlineDocumentText />,
  sharedComponentDoc: <HiOutlineShare />,
  utilsDoc: <HiOutlineVariable />,
  changeLog: <HiOutlineCode />,
  home: <HiOutlineHome />,
  package: <HiOutlineGift />,
  taxation: <HiOutlineDatabase />,
  addons: <HiOutlinePlusCircle />,
  tags:<BsTags/>,
  catalogues:<MdOutlineBookmarks/>,
  categories:<HiOutlineTag/>,
  orderManagement:<AiOutlineOrderedList/>,
  userManagement:<HiOutlineUserGroup/>,
  content:<MdOutlineContentCopy/>,
  bag: <HiOutlineShoppingBag />,
};

export default navigationIcon;
